apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice
  namespace: default
  labels:
    app: python-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
        - name: python-microservice
          image: your-ecr-repo-url:tag
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: python-microservice-config
                  key: DATABASE_URL
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always
