apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: python-microservice
  namespace: default
spec:
  hosts:
  - "*" 
  gateways:
  - python-microservice-gateway
  http:
  - match:
    - uri:
        prefix: /items
    - uri:
        prefix: /docs
    route:
    - destination:
        host: python-microservice.default.svc.cluster.local
        port:
          number: 8000
